#!/usr/bin/env python3
"""Render the canonical reduced-sphere NSA report as one reader-oriented PDF."""

from __future__ import annotations

import argparse
import html
import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Final

import markdown

REPOSITORY_ROOT: Final[Path] = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE: Final[Path] = (
    REPOSITORY_ROOT / "docs/research/reduced-sphere-nsa/report-source.md"
)
DEFAULT_OUTPUT: Final[Path] = (
    REPOSITORY_ROOT / "output/pdf/hevea-reduced-sphere-nsa-for-alok.pdf"
)
RUNTIME_NODE: Final[Path] = Path(
    "/Users/alokbeniwal/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/bin/node"
)
RUNTIME_NODE_MODULES: Final[Path] = Path(
    "/Users/alokbeniwal/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules"
)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--keep-html", action="store_true")
    return parser.parse_args()


def simulator_plate() -> str:
    candidates = [
        (
            "Atlas · the reduced ball as an object",
            REPOSITORY_ROOT / "docs/screenshots/sphere-atlas-visionos-26-5.png",
        ),
        (
            "Habitat · foot-scale controls; underfoot shell below frame",
            REPOSITORY_ROOT / "docs/screenshots/sphere-habitat-visionos-26-5.png",
        ),
        (
            "Hover · signed-altitude controls; near-field shell below frame",
            REPOSITORY_ROOT / "docs/screenshots/sphere-hover-visionos-26-5.png",
        ),
        (
            "Interior · the containing-ball gauge",
            REPOSITORY_ROOT / "docs/screenshots/sphere-interior-visionos-26-5.png",
        ),
    ]
    available = [(caption, path) for caption, path in candidates if path.is_file()]
    if not available:
        return ""

    figures = "".join(
        "<figure>"
        f'<img class="exhibit-image" src="{path.resolve().as_uri()}" '
        f'alt="{html.escape(caption)}">'
        f"<figcaption>{html.escape(caption)}</figcaption>"
        "</figure>"
        for caption, path in available
    )
    return (
        '<section class="visual-plate page-break-after">'
        '<div class="kicker">THE FOUR GAUGES · SIMULATOR EVIDENCE</div>'
        '<h2>One address. Four honest views.</h2>'
        '<p class="plate-note">These are generated by Hevea Vision on a finite '
        'REAL-TIME PROXY mesh. They visualize the model; they do not certify the '
        "paper's limiting isometry or physical-headset comfort. Habitat and "
        "Hover retain their semantic HUD receipts, while the underfoot surface "
        "falls below the simulator's forward capture.</p>"
        f'<div class="plate-grid">{figures}</div>'
        "</section>"
    )


def markdown_to_body(source: str) -> str:
    return markdown.markdown(
        source,
        extensions=[
            "fenced_code",
            "sane_lists",
            "tables",
            "toc",
            "pymdownx.arithmatex",
        ],
        extension_configs={
            "pymdownx.arithmatex": {
                "generic": True,
                "block_tag": "div",
            }
        },
        output_format="html5",
    )


def extract_title(body: str) -> tuple[str, str]:
    pattern = re.compile(r'<h1(?: id="[^"]+")?>(.*?)</h1>', re.DOTALL)
    match = pattern.search(body)
    if match is None:
        return "A sphere inside a point", body
    title = re.sub(r"<[^>]+>", "", match.group(1))
    return html.unescape(title), body[: match.start()] + body[match.end() :]


def decorate_claims(body: str) -> str:
    for label, class_name in (
        ("PAPER", "paper"),
        ("NSA-EQUIV", "nsa"),
        ("NEW-COROLLARY", "new"),
        ("APP-MODEL", "app"),
        ("OPEN", "open"),
    ):
        body = body.replace(
            f"[{label}]",
            f'<span class="claim claim-{class_name}">{label}</span>',
        )
    return body


def document_html(title: str, body: str, source_name: str) -> str:
    escaped_title = html.escape(title)
    plate = simulator_plate()
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{escaped_title}</title>
  <script>
    window.MathJax = {{
      options: {{ ignoreHtmlClass: '.*', processHtmlClass: 'arithmatex' }},
      chtml: {{ scale: 0.91 }},
      startup: {{
        ready: () => {{
          MathJax.startup.defaultReady();
          MathJax.startup.promise.then(() => {{
            document.documentElement.dataset.mathReady = 'true';
          }});
        }}
      }}
    }};
  </script>
  <script defer src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  <style>
    :root {{
      --ink: #172033;
      --muted: #5d697d;
      --line: #d9dfeb;
      --navy: #08172b;
      --cyan: #17c3d6;
      --gold: #d7aa4f;
      --ivory: #fffaf0;
      --violet: #826bd8;
    }}
    * {{ box-sizing: border-box; }}
    html {{ -webkit-print-color-adjust: exact; print-color-adjust: exact; }}
    body {{
      margin: 0;
      color: var(--ink);
      font-family: "Avenir Next", Avenir, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      font-size: 10.2pt;
      line-height: 1.53;
      letter-spacing: 0.002em;
    }}
    .cover {{
      min-height: 8.75in;
      margin: -0.62in -0.68in -0.68in;
      padding: 0.78in 0.78in 0.68in;
      color: white;
      background:
        radial-gradient(circle at 80% 15%, rgba(215,170,79,.34), transparent 32%),
        radial-gradient(circle at 18% 80%, rgba(23,195,214,.24), transparent 36%),
        linear-gradient(145deg, #050b17 0%, #0a1e37 50%, #190f2e 100%);
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      page-break-after: always;
      position: relative;
      overflow: hidden;
    }}
    .cover::after {{
      content: "";
      position: absolute;
      width: 5.3in;
      height: 5.3in;
      right: -1.65in;
      top: 1.22in;
      border: 1px solid rgba(255,255,255,.15);
      border-radius: 50%;
      box-shadow: 0 0 0 24px rgba(215,170,79,.035), 0 0 0 48px rgba(23,195,214,.025);
    }}
    .cover .overline, .kicker {{
      font-size: 8.5pt;
      font-weight: 750;
      letter-spacing: .18em;
      text-transform: uppercase;
      color: var(--cyan);
    }}
    .cover h1 {{
      max-width: 6.4in;
      margin: 0.45in 0 0.18in;
      font-size: 37pt;
      line-height: 1.02;
      letter-spacing: -.035em;
      color: white;
      position: relative;
      z-index: 1;
    }}
    .cover .subtitle {{
      max-width: 5.9in;
      color: #d8e4f4;
      font-size: 15pt;
      line-height: 1.35;
      position: relative;
      z-index: 1;
    }}
    .cover .thesis {{
      max-width: 5.7in;
      padding: .18in .22in;
      border-left: 3px solid var(--gold);
      background: rgba(255,255,255,.055);
      color: #f8f2e2;
      font-size: 12pt;
      position: relative;
      z-index: 1;
    }}
    .cover .meta {{
      display: flex;
      justify-content: space-between;
      gap: .2in;
      color: #aabbd0;
      font-size: 8.5pt;
      position: relative;
      z-index: 1;
    }}
    main {{ max-width: 100%; }}
    h1, h2, h3, h4 {{ color: var(--navy); page-break-after: avoid; }}
    h1 {{ font-size: 24pt; margin: .42in 0 .18in; }}
    h2 {{
      font-size: 17.5pt;
      margin: .34in 0 .14in;
      padding-top: .08in;
      border-top: 1px solid var(--line);
      letter-spacing: -.018em;
    }}
    h3 {{ font-size: 13pt; margin: .23in 0 .08in; color: #223b5c; }}
    h4 {{ font-size: 10.7pt; text-transform: uppercase; letter-spacing: .06em; }}
    p {{ margin: .08in 0 .12in; orphans: 3; widows: 3; }}
    a {{ color: #087f92; text-decoration: none; overflow-wrap: anywhere; }}
    blockquote {{
      margin: .18in 0;
      padding: .12in .18in;
      border-left: 3px solid var(--gold);
      background: #fff8e8;
      color: #3b4250;
      font-size: 11.2pt;
      page-break-inside: avoid;
    }}
    ul, ol {{ padding-left: .26in; margin: .08in 0 .13in; }}
    li {{ margin: .035in 0; }}
    table {{
      width: 100%;
      border-collapse: collapse;
      margin: .14in 0 .2in;
      font-size: 8.35pt;
      line-height: 1.32;
    }}
    thead {{ display: table-header-group; }}
    tr {{ page-break-inside: avoid; }}
    th {{
      background: var(--navy);
      color: white;
      text-align: left;
      font-weight: 700;
      padding: .07in .075in;
    }}
    td {{ border-bottom: 1px solid var(--line); padding: .065in .075in; vertical-align: top; }}
    tbody tr:nth-child(even) {{ background: #f7f9fc; }}
    code {{
      font-family: "SFMono-Regular", Menlo, Consolas, monospace;
      font-size: .88em;
      color: #143a52;
      background: #edf4f7;
      padding: .01in .035in;
      border-radius: 3px;
    }}
    pre {{
      margin: .14in 0 .2in;
      padding: .14in .16in;
      background: #07172a;
      color: #dbeafe;
      border-radius: 8px;
      white-space: pre-wrap;
      overflow-wrap: anywhere;
      line-height: 1.38;
      page-break-inside: avoid;
    }}
    pre code {{ color: inherit; background: transparent; padding: 0; }}
    .arithmatex {{ overflow: hidden; }}
    mjx-container[display="true"] {{
      margin: .14in 0 !important;
      page-break-inside: avoid;
      overflow: visible !important;
    }}
    .claim {{
      display: inline-block;
      padding: .018in .06in;
      border-radius: 999px;
      font-size: 7.1pt;
      line-height: 1.3;
      letter-spacing: .05em;
      font-weight: 800;
      vertical-align: .08em;
      white-space: nowrap;
    }}
    .claim-paper {{ background: #e5f7fa; color: #08798a; }}
    .claim-nsa {{ background: #eeeafb; color: #5740a7; }}
    .claim-new {{ background: #fff0ca; color: #825b0b; }}
    .claim-app {{ background: #e9f5e8; color: #2d6d31; }}
    .claim-open {{ background: #f3e8ef; color: #81385f; }}
    hr {{ border: 0; border-top: 1px solid var(--line); margin: .28in 0; }}
    .visual-plate {{ min-height: 8.3in; padding-top: .1in; }}
    .visual-plate h2 {{ border: 0; margin-top: .08in; font-size: 25pt; }}
    .plate-note {{ color: var(--muted); max-width: 6.5in; }}
    .plate-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: .16in; margin-top: .22in; }}
    figure {{ margin: 0; page-break-inside: avoid; }}
    .exhibit-image {{ width: 100%; max-height: 2.78in; object-fit: cover; border-radius: 9px; border: 1px solid #d4dbe6; }}
    figcaption {{ margin-top: .055in; color: #34445b; font-size: 8.4pt; font-weight: 650; }}
    .page-break-after {{ page-break-after: always; }}
    @media print {{
      a {{ color: #087f92; }}
      .cover {{ min-height: 8.63in; }}
    }}
  </style>
</head>
<body>
  <section class="cover">
    <div>
      <div class="overline">HEVEA VISION · A PERSONAL RESEARCH EDITION FOR ALOK SINGH</div>
      <h1>{escaped_title}</h1>
      <div class="subtitle">A faithful reconstruction of the reduced-sphere paper in nonstandard analysis, with one new scale-loss theorem and its spatial-computing consequences.</div>
    </div>
    <div class="thesis">The address is the geometry. The rendered point is only the current observation of it.</div>
    <div class="meta"><span>Canonical source: {html.escape(source_name)}</span><span>29 AUGUST 2026 · UNOFFICIAL RESEARCH COMPANION</span></div>
  </section>
  {plate}
  <main>{body}</main>
</body>
</html>"""


def discover_node() -> Path:
    configured = os.environ.get("HEVEA_NODE_PATH")
    if configured:
        return Path(configured)
    if RUNTIME_NODE.is_file():
        return RUNTIME_NODE
    return Path("node")


def render_pdf(html_path: Path, output_path: Path) -> dict[str, int]:
    environment = os.environ.copy()
    configured_modules = environment.get("NODE_PATH")
    if configured_modules is None and RUNTIME_NODE_MODULES.is_dir():
        environment["NODE_PATH"] = str(RUNTIME_NODE_MODULES)
    printer = REPOSITORY_ROOT / "Scripts/print-html-pdf.mjs"
    completed = subprocess.run(
        [str(discover_node()), str(printer), str(html_path), str(output_path)],
        cwd=REPOSITORY_ROOT,
        env=environment,
        check=True,
        capture_output=True,
        text=True,
    )
    line = completed.stdout.strip().splitlines()[-1]
    receipt = json.loads(line)
    return {str(key): int(value) for key, value in receipt.items()}


def main() -> int:
    arguments = parse_arguments()
    source_path = arguments.source.resolve()
    output_path = arguments.output.resolve()
    if not source_path.is_file():
        raise FileNotFoundError(source_path)

    source = source_path.read_text(encoding="utf-8")
    body = decorate_claims(markdown_to_body(source))
    title, body = extract_title(body)
    rendered = document_html(title, body, source_path.name)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    html_path = output_path.with_suffix(".html")
    html_path.write_text(rendered, encoding="utf-8")
    try:
        receipt = render_pdf(html_path, output_path)
    finally:
        if not arguments.keep_html and html_path.exists():
            html_path.unlink()

    if not output_path.is_file() or output_path.stat().st_size < 100_000:
        raise RuntimeError("PDF output is missing or unexpectedly small")
    print(
        json.dumps(
            {
                "output": str(output_path),
                "bytes": output_path.stat().st_size,
                **receipt,
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
